"""
Django settings for xdbg project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

LOGIN_URL = "/login"
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FRONTEND_RULES = ['no01', 'no02', 'no03', 'no04', 'no05', 'no06', 'no07', 'no08', 'no09', 'no10', 'no11', 'no12',
                  'no13', 'no14', 'no15', 'no16', 'no17', 'no18', 'no20', 'no21', 'no22', 'no23', 'no24', 'no25',
                  'no26','no27','no28','no29','no30','no31','no32','no33',"no34"]
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vqvjfp&i2mcz=by#ja$in@mji30&206+e#!s1lcz(t(5(t7tnv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.1.223", "127.0.0.1", "192.168.1.183"]
SESSION_COOKIE_AGE = 60 * 30
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_NAME = "sdcookie"
SESSION_COOKIE_PATH = "/"
# CSRF_HEADER_NAME = "sdcsrf"
# CSRF_USE_SESSIONS=True
# CSRF_SESSION_KEY="sdcsrf"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "center",
    "policycenter",
    "modelcenter",
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # "xdbg.Middleware.MyMiddle",
]

ROOT_URLCONF = 'xdbg.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xdbg.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# REDIS_HOST="192.168.1.183"
REDIS_HOST="127.0.0.1"
REDIS_PORT=6379

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'NAME': "yunyingshang_qianzhi_moxing",
        "HOST": "118.178.232.100",
        # "HOST":"192.168.1.183",
        "PORT": "3306",
        # "USER":"bigdata",
        "USER": "kankan",
        "PASSWORD": "DATADIG123456",
        # "PASSWORD":"bigdata123456",
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },

}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'xdbg', 'static'),
    os.path.join(BASE_DIR, 'helpcenter', 'static'),
    os.path.join(BASE_DIR, 'policycenter', 'static'),
    os.path.join(BASE_DIR, 'modelcenter', 'static'),
    os.path.join(BASE_DIR, 'center', 'static'),
]

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': '192.168.1.183:11211',
#         "KEY_FUNCTION": lambda key, key_prefix, version: "django:"+key,
#         "TIMEOUT":60*60,
#     }
# }


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "KEY_FUNCTION": lambda key, key_prefix, version: "django:" + key,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
